### PR TITLE
Release 1.2.0-4

### LINKED ISSUE #125: [BP-588] Spawner logs are multiplied x2, x4, x5 and some are x11
Have you checked our docs before proceeding?
- [x] [Documentation](https://flow.mov.ai/docs)
- [x] [Discourse](https://forum.flow.mov.ai/)

### Issue Description
Spawner logs are multiplied x2, x4, x5 and some are x11

### Steps to Reproduce

  1. Install movai-flow 1.2.0-1
  2. Launch the IDE using the desktop icon
  3. Run the first example flow in the welcome screen (husky_simple_navigation)
  4. Check the docker logs (`docker logs spawner-robot1 -f`)

#### Actual Behaviour
A lot of duplicated logs
image

#### Expected Behaviour
Each different log should be printed once

### Versions

- movai-flow: 1.2.0-1

- movai-ide: 3.0.0-4

### Possible workarounds

- None

### Additional Details

- Installed packages: N/A

### LINKED ISSUE #127: [BP-585] Export of metadata using the backup tool is broken, import functionality seems to be working
Have you checked our docs before proceeding?
- [x] [Documentation](https://flow.mov.ai/docs)
- [x] [Discourse](https://forum.flow.mov.ai/)

### Issue Description
Export of metadata using the backup tool is broken, import functionality seems to be working

### Steps to Reproduce

  1. Install movai-flow 1.2.0-1
  2. Go to `Documents/MovaiFlow/userspace` and make a `cache/ros/src` dir
```
cd ~/Documents/MovaiFlow/userspace
```
  3. Clone the [sample project](https://github.com/MOV-AI/movai_ce_demos)
  4. Go to spawner container  
```
docker exec -ti spawner-robot1 bash
```
 5. import all the metadata
```
python3.8 -m tools.backup -a import -r ~/user/cache/ros/src/movai_ce_demos/ -p metadata -m ~/user/cache/ros/src/movai_ce_demos/manifest.txt
```
  6. Confirm no errors
  7. export all the metadata
```
python3.8 -m tools.backup -a export -r ~/user/cache/ros/src/movai_ce_demos/ -p metadata -m ~/user/cache/ros/src/movai_ce_demos/manifest.txt
```
  8. Confirm the below error

#### Actual Behaviour

image

#### Expected Behaviour

Export of all the items that is mentioned in the manifest file

### Versions

- movai-flow: 1.2.0-1

- movai-ide: 3.0.0-4

### Possible workarounds

- None

### Additional Details

- N/A

### PR DESCRIPTION
**Pull request by MithunKinarullathil**
## Content

Fixes #127 
Fixes #125 
- Use latest public world launcher ignition plugin (#139)
- Update of movai_ce_demos package (#137)

--- 

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

### CODE REVIEW

**Comment by AlexFernandes-MOVAI** [comment]
@engdorm @Mograbi , please make sure everything is aligned with:

> dal 1.0.0.29
> shared 1.0.0.10
> backend 1.0.0.23

**Comment by engdorm** [comment]
@AlexFernandes-MOVAI we will prepare a new version of spawner as well 
and only then create a new version of movai-flow

**Comment by MithunKinarullathil** [comment]
> @AlexFernandes-MOVAI we will prepare a new version of spawner as well and only then create a new version of movai-flow

Yes, this PR will wait till the required images are there. Thanks.

**Comment by MithunKinarullathil** [comment]
- Export tool is working
- Logs are working as well

image

**Review by AlexFernandes-MOVAI — APPROVED** [review]

**Pull request merged**
