### PR TITLE
Feat: language server

### PR DESCRIPTION
**Pull request by AlexFernandes-MOVAI**
## Content

- Added service for language server in docker-compose
- Added haproxy configuration to expose the websocket on http://localhost:8080/lsp/
- Updated application IDE-CE for lsp support

@PedroCristovao-Movai and @RianMartins-Movai , please review IDE-CE to use correct endpoint

### CODE REVIEW

**Comment by MithunKinarullathil** [comment]
Hi @AlexFernandes-MOVAI. I've talked with @almeidamov and we concluded that we will add this to the tests once we have confirmation of completion from you. This is to not start testing before it's ready and better organize the testing phase.

**Comment by PedroCristovao-Movai** [comment]
The frontend part is done, we just need a new release of the [backend](https://github.com/MOV-AI/backend) for the language server to function properly. 

@MOV-AI/backend-team

**Comment by PedroCristovao-Movai** [comment]
@AlexFernandes-MOVAI @engdorm 

Waiting to get the latest backend release

**Comment by AlexFernandes-MOVAI** [comment]
@engdorm @PedroCristovao-Movai when launching https://github.com/MOV-AI/backend/releases/tag/1.0.0.27 the webserver is not working

**Comment by almeidamov** [comment]
Not to enter in October 2022 version

**Comment by AlexFernandes-MOVAI** [comment]
PR is on hold until container backend built from https://github.com/MOV-AI/backend is OK

**Comment by MithunKinarullathil** [comment]
BE Should be available above this release: https://github.com/MOV-AI/backend/releases/tag/1.0.0.26

**Comment by MithunKinarullathil** [comment]
Stale PR, please RE-Open if relevant in the future.

**Pull request closed without merging**
