### PR TITLE
Pre-release 1.2.0-2

### PR DESCRIPTION
**Pull request by MithunKinarullathil**
### Pre-release 1.2.0-2

- Update Debian control (#103)
- Update movai-ide-ce (#104)
  - More updates (#114) 
- Review description of desktop shortcuts (#105)
- Fix: Log-level is set to warning, missing debug and prints in docker logs (#106)
- Fix: Spelling error on the examples (#107)
- Fix: Haproxy not being removed on movai-flow purge (#111)
- Fix: [Not being able to search MOV.AI ignition icon](https://movai.atlassian.net/browse/CSAI-1889) 
- Fix : [DP-703 - use standard dynamic release pipeline](#100) 
- Public repositories usage only (#109)
- DP-686 : Fix recreated containers on reboot (#110)

@oferKatz07 @RianMartins-Movai You can update this list once you have the PRs ready with your changes. 
@AlexFernandes-MOVAI @almeidamov @xsoulp FYI. :)

### CODE REVIEW

**Comment by AlexFernandes-MOVAI** [comment]
> not ready yet

ready after merging : https://github.com/MOV-AI/movai-flow/pull/109

**Review by AlexFernandes-MOVAI — CHANGES_REQUESTED** [review]
@engdorm and @Mograbi : the flow not starting issue is back

Packages on spawner:
- dal==1.0.0.26
- flow-initiator==1.0.1.7
- gd-node==1.0.0.8
- movai-core-shared==1.0.0.9

Package on backend:
- backend==1.0.0.21
- dal==1.0.0.26
- gd-node==1.0.0.8

**Review by AlexFernandes-MOVAI — APPROVED** [review]
Tested OK on my laptop:
- installation from deb
- uninstallation/purge with apt
- rviz ROS time OK
- simulator OK
- start flow OK

**Comment by MithunKinarullathil** [comment]
> Tested OK on my laptop:
> 
> * installation from deb
> * uninstallation/purge with apt
> * rviz ROS time OK
> * simulator OK
> * start flow OK

Great, thanks.

**Pull request merged**
