### PR TITLE
Update IDE-CE

### LINKED ISSUE #233: Not able to load more flows after we run the first demo flow
Have you checked our docs before proceeding?
- [x] [Documentation](https://flow.mov.ai/docs)
- [x] [Discourse](https://forum.flow.mov.ai/)

### Issue Description
Once the IDE is up, we can open and run the first demo flow (husky simple navigation). Once the flow is stopped, the rest of the flow is not opening from the examples menu.

### Steps to Reproduce

  1. Once the IDE is up try running the first demo
  2. Stop the flow
  3. Try opening the second demo.

#### Actual Behaviour
The flow fails to load

#### Expected Behaviour
The flow should be opening as normal

### Versions

- movai-flow: dev

- movai-ide: 3.1.0-3

### Possible workarounds

- Refresh the page

### PR DESCRIPTION
**Pull request by diasnad**
Fixes #233 

## Proposed Changes
  - Update the IDE version to 3.1.0-4

- [ ] ~~Make sure you are opening from a **topic/feature/bugfix branch**~~
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changesOpen a pull request
- [x] Link to relevant issues in GitHub or Jira
- [ ] ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- [ ] ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

### CODE REVIEW

**Comment by AlexFernandes-MOVAI** [comment]
@MithunKinarullathil and  @diasnad  what do we do with this PR , still a draft ?

**Comment by MithunKinarullathil** [comment]
> @MithunKinarullathil and @diasnad what do we do with this PR , still a draft ?

Some PR checks seem to be failing. I remember I had a conversation about it with @diasnad. I don't remember what we had decided. @diasnad Can we get an update on this please.?

**Comment by diasnad** [comment]
I will passe it to @quirinpa to check on the failed tests. Sorry for the delay in the response

**Comment by MithunKinarullathil** [comment]
Duplicated by #238

**Pull request closed without merging**
