### PR TITLE
Bump version of FE app to 3.0.0-8

### PR DESCRIPTION
**Pull request by RianMartins-Movai**
Bump version of FE app to 3.0.0-8

- [FP-1749 : Select default robot if currently saved ID is not in the robot list](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/188)
- [FP-1795 : Invalid parameters were not being showned to the user](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/191)
- [FP-1637 : Resize node after adding/removing ports in the template](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/194)
- [FP-1796 : Add new tabs to stack and refactor useTabStack hook](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/195)
- [FP-1812 : Enable new internal user to auth in IDE-CE](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/198)
- [FP-1761 : Prevent browser context menu](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/201)
- [FP-1716 : Show unknown node types as white](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/202)
- [FP-1780 : Open context menu regardless of already being one previously open](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/204)
- [FP-1839 : New snackbar is not appearing and/or crashing app](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/205)
- [FP-1853 : Migrate key shortcuts](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/206)
- [FP-1838 : Give focus to active editor if it becomes dirty](https://github.com/MOV-AI/frontend-npm-ide-ce/pull/214)

### CODE REVIEW

**Review by AlexFernandes-MOVAI — APPROVED** [review]

**Review by AlexFernandes-MOVAI — CHANGES_REQUESTED** [review]
this package is not available on public repository here:
https://artifacts.aws.cloud.mov.ai/#browse/browse:ppa-public:packages%2Fm%2Fmovai-ide-ce

**Review by AlexFernandes-MOVAI — DISMISSED** [review]
version is now available on ppa-public

**Comment by AlexFernandes-MOVAI** [comment]
@almeidamov and @diasdm up to you to decide if we merge this before RC or not

**Comment by almeidamov** [comment]
We will check how testing evolves and validate the available time to test it in this release

**Comment by MithunKinarullathil** [comment]
If we have time to test, this will be merged but for now, it's a draft.

**Comment by MithunKinarullathil** [comment]
No longer relevant.

**Pull request closed without merging**
